# Generated by Django 4.1.7 on 2023-04-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestudent',
            name='teachers',
            field=models.ManyToManyField(related_name='students', through='tutor.Lesson', to='tutor.profileteacher'),
        ),
    ]
